import { useState, useEffect } from 'react';
import { useLocation, Link, useNavigate } from 'react-router-dom';
import { Printer, ArrowLeft, Loader2 } from 'lucide-react';
import CarePlanDisplay from '../components/CarePlanDisplay';
import CDSSPanel from '../components/cdss/CDSSPanel';
import { useAuth } from '../context/AuthContext';

const PatientCareView = () => {
    const { state } = useLocation();
    const navigate = useNavigate();
    const { user } = useAuth();

    // If plan is passed via state (e.g., from a redirect), use it.
    // Otherwise, start null to show the CDSS Panel for generation.
    const [plan, setPlan] = useState(state?.plan || null);

    const API_BASE = '/api'; // Use proxy

    // If we have a plan, render the display
    if (plan) {
        return (
            <div className="min-h-screen bg-slate-50 py-8 px-4 sm:px-6 lg:px-8">
                <div className="max-w-5xl mx-auto">
                    {/* Header */}
                    <div className="flex justify-between items-center mb-6">
                        <button
                            onClick={() => navigate('/dashboard')}
                            className="flex items-center text-slate-600 hover:text-slate-900 transition"
                        >
                            <ArrowLeft className="h-5 w-5 mr-2" />
                            Back to Dashboard
                        </button>
                        <button
                            onClick={() => window.print()}
                            className="flex items-center text-teal-600 hover:text-teal-700 font-medium"
                        >
                            <Printer className="h-5 w-5 mr-2" />
                            Print Plan
                        </button>
                    </div>

                    <CarePlanDisplay
                        carePlan={plan}
                        reasoning={state?.reasoning || { totalRules: 0, paths: [] }}
                    />

                    <div className="mt-8 text-center text-xs text-slate-400">
                        Generated by SecureMed CDSS
                    </div>
                </div>
            </div>
        );
    }

    // If no plan, show the CDSS Panel to generate one
    return (
        <div className="py-8 px-4 sm:px-6 lg:px-8 bg-slate-50 min-h-screen">
            <div className="max-w-4xl mx-auto">
                <div className="mb-8">
                    <button
                        onClick={() => navigate('/dashboard')}
                        className="flex items-center text-slate-600 hover:text-slate-900 transition mb-4"
                    >
                        <ArrowLeft className="h-5 w-5 mr-2" />
                        Back to Dashboard
                    </button>
                    <h1 className="text-2xl font-bold text-slate-900 mb-2">My Care Plan</h1>
                    <p className="text-slate-500">Generate your personalized care plan using your secure diagnosis file.</p>
                </div>

                <CDSSPanel
                    apiBase={API_BASE}
                />
            </div>
        </div>
    );
};

export default PatientCareView;

