import { useState, useEffect } from 'react';
import { useLocation, Link, useNavigate } from 'react-router-dom';
import { Printer, ArrowLeft, Loader2 } from 'lucide-react';
import { generateCarePlan } from '../api/mockCarePlan';
import CarePlanDisplay from '../components/CarePlanDisplay';

const PatientCareView = () => {
    const { state } = useLocation();
    const navigate = useNavigate();
    const [plan, setPlan] = useState(state?.plan || null);
    const [loading, setLoading] = useState(!state?.plan);

    useEffect(() => {
        if (!plan) {
            const fetchPlan = async () => {
                setLoading(true);
                try {
                    // Fetch Mock Data
                    const rawPlan = await generateCarePlan('Diabetes Type 2', 'current-user');

                    // Map to CarePlanDisplay format
                    const formattedPlan = {
                        patientName: 'You',
                        diagnosis: { name: rawPlan.diagnosisNormalized || 'Unknown Condition' },
                        generatedAt: new Date().toISOString(),
                        treatments: (rawPlan.medications || []).map((m, i) => ({
                            id: `med-${i}`,
                            name: m.name,
                            dosage: m.dosage,
                            priority: 1,
                            examples: []
                        })),
                        dietPlan: (rawPlan.diet || []).map((d, i) => ({
                            id: `diet-${i}`,
                            name: d.text,
                            description: d.reason,
                            priority: 2
                        })),
                        warnings: (rawPlan.alerts || []).map((a, i) => ({
                            message: a.message,
                            severity: a.type === 'warning' ? 'medium' : 'high',
                            type: 'general'
                        })),
                        monitoring: (rawPlan.lifestyle || []).map(l => l.text),
                        excludedTreatments: []
                    };

                    setPlan(formattedPlan);
                } catch (err) {
                    console.error("Failed to load care plan", err);
                } finally {
                    setLoading(false);
                }
            };
            fetchPlan();
        }
    }, []);

    if (loading) {
        return (
            <div className="min-h-screen flex flex-col items-center justify-center bg-slate-50">
                <Loader2 className="h-10 w-10 text-teal-600 animate-spin mb-4" />
                <p className="text-slate-500 font-medium">Generating your personalized Health Plan...</p>
            </div>
        );
    }

    if (!plan) {
        return (
            <div className="p-8 text-center">
                <p>No Care Plan available.</p>
                <Link to="/dashboard" className="text-teal-600 font-medium mt-4 inline-block">Back to Dashboard</Link>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-slate-50 py-8 px-4 sm:px-6 lg:px-8">
            <div className="max-w-5xl mx-auto">
                {/* Header */}
                <div className="flex justify-between items-center mb-6">
                    <button
                        onClick={() => navigate('/dashboard')}
                        className="flex items-center text-slate-600 hover:text-slate-900 transition"
                    >
                        <ArrowLeft className="h-5 w-5 mr-2" />
                        Back to Dashboard
                    </button>
                    <button
                        onClick={() => window.print()}
                        className="flex items-center text-teal-600 hover:text-teal-700 font-medium"
                    >
                        <Printer className="h-5 w-5 mr-2" />
                        Print Plan
                    </button>
                </div>

                {/* We render the ported CarePlanDisplay component here */}
                <CarePlanDisplay
                    carePlan={plan}
                    reasoning={{
                        totalRules: 5, // Mock count
                        paths: [
                            { ruleId: 'R-DM-01', reason: 'Diagnosis matches Type 2 Diabetes criteria', category: 'inclusion', timestamp: new Date().toISOString() },
                            { ruleId: 'R-MED-12', reason: 'Metformin recommended as first-line therapy', category: 'treatment', timestamp: new Date().toISOString() }
                        ]
                    }}
                />

                <div className="mt-8 text-center text-xs text-slate-400">
                    Generated by SecureMed CDSS • Reviewed by Dr. Smith
                </div>
            </div>
        </div>
    );
};

export default PatientCareView;
